version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3326:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - "./vendor:/var/www/html/test/vendor"
      - "./app/wp:/var/www/html/test/app/wp"
      - .:/var/www/html/test
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      XDEBUG_CONFIG: "remote_host=docker.for.mac.localhost remote_port=9000"
      PHP_IDE_CONFIG: "serverName=wpsite"
